import { 
  Smartphone, Zap, Sofa, Plane, GamepadIcon, Car, Book, Heart, Award, BookOpen,
  Music, Film, Coffee, Dog, Cat, Trees, Camera, Laptop, Watch, ShoppingBag, PenTool, Cake, Bike, Caravan,
  Cpu, Database, Diamond, Flame, Globe, Handshake, Home, Key, Lightbulb, Mail, Map, Banknote, Moon,
  Pencil, Phone, PieChart, Printer, ShoppingCart, Sun, Trash, Truck, User, Users, Wifi, Workflow,
  Ticket, Star, Clock, Shield, Sparkles, Shirt, FolderTree, Footprints,
  Store, Package, Gift, Utensils, Pizza, Apple, Leaf, Sprout, Dumbbell, Baby, PawPrint, Headphones,
  Monitor, Tv, Wrench, Palette, GraduationCap, Briefcase, Wallet, BadgePercent, Building2, Gamepad2
} from 'lucide-react';

import { GiClothes, GiLipstick } from 'react-icons/gi';
import { MdCategory } from 'react-icons/md';
import { FaFire } from 'react-icons/fa';

export const lucideIcons: Record<string, any> = {
  'FaFire': FaFire,
  'Smartphone': Smartphone,
  'Zap': Zap,
  'Sofa': Sofa,
  'Plane': Plane,
  'GamepadIcon': GamepadIcon,
  'Car': Car,
  'Book': Book,
  'Heart': Heart,
  'Award': Award,
  'BookOpen': BookOpen,
  'MdCategory': MdCategory,
  'Tag': Ticket, 
  'Ticket': Ticket,
  'Music': Music,
  'Film': Film,
  'Coffee': Coffee,
  'Dog': Dog,
  'Cat': Cat,
  'Tree': Trees,
  'Camera': Camera,
  'Laptop': Laptop,
  'Watch': Watch,
  'Bag': ShoppingBag,
  'PenTool': PenTool,
  'Cake': Cake,
  'Bike': Bike,
  'Caravan': Caravan,
  'Cpu': Cpu,
  'Database': Database,
  'Diamond': Diamond,
  'Flame': Flame,
  'Globe': Globe,
  'Handshake': Handshake,
  'Home': Home,
  'Key': Key,
  'Lightbulb': Lightbulb,
  'Mail': Mail,
  'Map': Map,
  'Money': Banknote,
  'Moon': Moon,
  'Pencil': Pencil,
  'Phone': Phone,
  'PieChart': PieChart,
  'Printer': Printer,
  'ShoppingCart': ShoppingCart,
  'Sun': Sun,
  'Trash': Trash,
  'Truck': Truck,
  'User': User,
  'Users': Users,
  'Wifi': Wifi,
  'Workflow': Workflow,
  'Star': Star,
  'Clock': Clock,
  'Shield': Shield,
  'Sparkles': Sparkles,
  'Shirt': Shirt,
  'ShoppingBag': ShoppingBag,
  'FolderTree': FolderTree,
  'GiClothes': GiClothes,
  'GiLipstick': GiLipstick,
  'Shoe': Footprints,
  'Store': Store,
  'Package': Package,
  'Gift': Gift,
  'Utensils': Utensils,
  'Pizza': Pizza,
  'Apple': Apple,
  'Leaf': Leaf,
  'Sprout': Sprout,
  'Dumbbell': Dumbbell,
  'Baby': Baby,
  'PawPrint': PawPrint,
  'Headphones': Headphones,
  'Monitor': Monitor,
  'Tv': Tv,
  'Wrench': Wrench,
  'Palette': Palette,
  'GraduationCap': GraduationCap,
  'Briefcase': Briefcase,
  'Wallet': Wallet,
  'BadgePercent': BadgePercent,
  'Building2': Building2,
  'Gamepad2': Gamepad2
};

export const defaultCategoryIcons: Record<string, string> = {
  'todos': 'FaFire',
  'tecnologia': 'Smartphone',
  'eletronicos': 'Zap',
  'eletrônicos': 'Zap',
  'informatica': 'Laptop',
  'informática': 'Laptop',
  'moda': 'Shirt',
  'vestuario': 'Shirt',
  'vestuário': 'Shirt',
  'roupas': 'Shirt',
  'acessorios': 'Watch',
  'acessórios': 'Watch',
  'beleza': 'Sparkles',
  'casa': 'Home',
  'moveis': 'Sofa',
  'móveis': 'Sofa',
  'viagem': 'Plane',
  'saude': 'Heart',
  'saúde': 'Heart',
  'esportes': 'Dumbbell',
  'educacao': 'GraduationCap',
  'educação': 'GraduationCap',
  'gastronomia': 'Utensils',
  'alimentos': 'Utensils',
  'entretenimento': 'Film',
  'games': 'GamepadIcon',
  'automoveis': 'Car',
  'automóveis': 'Car',
  'livros': 'Book',
  'pets': 'PawPrint',
  'infantil': 'Baby',
  'mercado': 'ShoppingCart',
  'financeiro': 'Wallet',
  'servicos': 'Briefcase',
  'serviços': 'Briefcase',
  'jardinagem': 'Leaf',
  'ofertas': 'BadgePercent',
  'cupons': 'Ticket',
  'imperdiveis': 'Flame',
  'imperdíveis': 'Flame',
  'informativos': 'BookOpen',
  'escritorio': 'Briefcase',
  'escritório': 'Briefcase',
  'construcao': 'Wrench',
  'construção': 'Wrench',
  'arte': 'Palette',
  'musica': 'Music',
  'música': 'Music',
  'cafes': 'Coffee',
  'cafés': 'Coffee',
  'doces': 'Cake',
  'pizzaria': 'Pizza',
  'mercado gourmet': 'Apple',
  'bebes': 'Baby',
  'bebês': 'Baby',
  'lojas': 'Store',
  'entrega': 'Truck',
  'servicos digitais': 'Monitor',
  'serviços digitais': 'Monitor'
};

export const getDefaultCategoryIconName = (category: string): string | null => {
  if (!category) return null;
  const normalized = category.trim().toLowerCase();
  return defaultCategoryIcons[normalized] || null;
};
